### PR TITLE
ISSUE-244: Adds Flavor aggregation at Parent ADO Level (2 levels up)

### PR DESCRIPTION
**Pull request by DiegoPino**
See #244 

Note: Since an HOCR will be generated after an ADO there might be moments where, after the Flavor is indexed and we sent the related (parent and parent of parent) to be tracked again, the index has again Content Entities that are marked but not updated yet. It is the only way and Cron/any other action will eventually catch up. 

This is because in this case the relationship is bi-directional! And there are only two trackers/ 2 queues for this. Still this is very impressive code and very advanced folks. Be proud of this

### CODE REVIEW

**Comment by patdunlavey** [comment]
Initial testing... I'm getting an error when adding the sbf_aggregated_items field. The edit link fails (ajax error), leaving this in the log:
```
TypeError: explode(): Argument #2 ($string) must be of type string, array given in explode() (line 40 of /var/www/html/web/modules/contrib/strawberryfield/src/Plugin/search_api/processor/Property/StrawberryFlavorAggregatedItemProperty.php)
#0 /var/www/html/web/modules/contrib/strawberryfield/src/Plugin/search_api/processor/Property/StrawberryFlavorAggregatedItemProperty.php(40): explode(',', Array)
#1 /var/www/html/web/modules/contrib/search_api/src/Form/FieldConfigurationForm.php(154): Drupal\strawberryfield\Plugin\search_api\processor\Property\StrawberryFlavorAggregatedItemProperty->buildConfigurationForm(Object(Drupal\search_api\Item\Field), Array, Object(Drupal\Core\Form\FormState))
#2 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityForm.php(106): Drupal\search_api\Form\FieldConfigurationForm->form(Array, Object(Drupal\Core\Form\FormState))
#3 /var/www/html/web/modules/contrib/search_api/src/Form/FieldConfigurationForm.php(141): Drupal\Core\Entity\EntityForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#4 [internal function]: Drupal\search_api\Form\FieldConfigurationForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#5 /var/www/html/web/core/lib/Drupal/Core/Form/FormBuilder.php(531): call_user_func_array(Array, Array)
```

I _think_ I have all the composer.json versions correct:
```
    "require": {
        "php": ">=7.3",
        "ext-json": "*",
        "archipelago/ami": "0.5.0.x-dev as 0.4.0.x-dev",
        "archipelago/archipelago_subtheme": "1.0.0.x-dev",
        "aws/aws-php-sns-message-validator": "^1.5",
        "aws/aws-sdk-php": "^3.63",
        "behat/mink": "^1.8",
        "behat/mink-selenium2-driver": "^1",
        "born-digital-us/bd-base-archi-modules": "dev-main",
        "born-digital-us/bd_archipelago_subtheme": "dev-main",
        "composer/installers": "^1.9",
        "composer/semver": "^3.2",
        "cweagans/composer-patches": "^1.6",
        "drupal/address": "^1.9",
        "drupal/addtoany": "^1.9",
        "drupal/adminimal_theme": "^1.6",
        "drupal/auditfiles": "^2.11",
        "drupal/backup_migrate": "^5.0",
        "drupal/bamboo_twig": "5.x-dev",
        "drupal/better_exposed_filters": "^5.0@beta",
        "drupal/bootstrap_barrio": "^5.1",
        "drupal/bulk_user_registration": "^1.1@beta",
        "drupal/calendar": "^1.0@alpha",
        "drupal/redis": "^1.5",
        "drupal/chosen": "^3.0",
        "drupal/config_filter": "^2.2",
        "drupal/config_ignore": "^2.3",
        "drupal/config_inspector": "dev-1.x",
        "drupal/config_split": "^2",
        "drupal/config_split_ignore": "^1.9",
        "drupal/config_update": "^1.6",
        "drupal/config_update_ui": "^1.6",
        "drupal/content_access": "^1.0@alpha",
        "drupal/context": "^4.0@beta",
        "drupal/core": "^9",
        "drupal/core-composer-scaffold": "^9",
        "drupal/core-project-message": "^9",
        "drupal/core-recommended": "^9.3",
        "drupal/devel": "4.x-dev@dev",
        "drupal/devel_php": "^1.5",
        "drupal/diff": "^1.0",
        "drupal/display_field_copy": "^2.0",
        "drupal/ds": "3.x-dev@dev",
        "drupal/entity": "^1.2",
        "drupal/entity_extra_field": "^2.0@alpha",
        "drupal/entityqueue": "^1.2",
        "drupal/environment_indicator": "^4.0",
        "drupal/facets": "^2.0",
        "drupal/fancy_file_delete": "^2.0",
        "drupal/field_group": "^3.1",
        "drupal/field_permissions": "^1.0@RC",
        "drupal/file_mdm": "^2",
        "drupal/file_mdm_exif": "^2",
        "drupal/flag": "^4.0",
        "drupal/fontawesome": "^2.17",
        "drupal/form_mode_manager": "^2.0@RC",
        "drupal/google_api_client": "^4.2",
        "drupal/group": "^1.3",
        "drupal/imagemagick": "^3.1",
        "drupal/imce": "^1.7",
        "drupal/inline_entity_form": "1.x-dev",
        "drupal/jquery_ui_datepicker": "^1.1",
        "drupal/jquery_ui_slider": "^1.1",
        "drupal/jquery_ui_touch_punch": "~1.0",
        "drupal/jsonapi_earlyrendering_workaround": "^1.0",
        "drupal/masquerade": "^2.0@beta",
        "drupal/migrate_plus": "^5.1",
        "drupal/migrate_tools": "^5.0",
        "drupal/migrate_upgrade": "^4",
        "drupal/moderated_content_bulk_publish": "^2.0",
        "drupal/paragraphs": "^1.12",
        "drupal/pathauto": "^1",
        "drupal/pcb": "^2.3",
        "drupal/queue_ui": "^3.1",
        "drupal/quick_node_clone": "^1.1",
        "drupal/redirect": "^1.7",
        "drupal/restui": "^1.1",
        "drupal/role_theme_switcher": "^1.1",
        "drupal/s3fs": "3.x-dev",
        "drupal/schema_metatag": "^1.3",
        "drupal/search_api": "^1.2",
        "drupal/search_api_attachments": "^1.0@beta",
        "drupal/search_api_autocomplete": "^1.2",
        "drupal/search_api_solr": "^4.2",
        "drupal/smtp": "^1.0",
        "drupal/tokenuuid": "^2.0",
        "drupal/twig_field": "^1.0",
        "drupal/twig_tweak": "^2.6",
        "drupal/variationcache": "^1.0",
        "drupal/viewfield": "^3.0@beta",
        "drupal/views_block_area": "^1.0@beta",
        "drupal/views_block_filter_block": "^1.0",
        "drupal/views_bootstrap": "^5.4",
        "drupal/views_bulk_operations": "4.1.2",
        "drupal/views_contextual_filters_or": "^1.3",
        "drupal/views_data_export": "^1.0",
        "drupal/views_display_switch": "^1.1",
        "drupal/webform": "^6",
        "drupal/webform_entity_handler": "1.x-dev",
        "drupal/webformnavigation": "^1.0@alpha",
        "drupal/workflow": "^1.1",
        "drush/drush": "10.5",
        "fileeye/mimemap": "^1.1.1",
        "maennchen/zipstream-php": "^2.1",
        "mixnode/mixnode-warcreader-php": "^0.0.6",
        "ml/json-ld": "^1.0",
        "mtdowling/jmespath.php": "^2.4",
        "netgen/query-translator": "dev-add-ranges-support",
        "npm-asset/nouislider": "^14",
        "oomphinc/composer-installers-extender": "^2.0",
        "pear/archive_tar": "^1.4.12",
        "ramsey/uuid": "^4.1",
        "react/child-process": "^0.6.1",
        "react/event-loop": "^1.1",
        "react/promise": "^2.7",
        "solarium/solarium": "^6.0",
        "strawberryfield/format_strawberryfield": "1.1.0.x-dev as 1.0.0.x-dev",
        "strawberryfield/strawberry_runners": "0.5.0.x-dev as 0.4.0.x-dev",
        "strawberryfield/strawberryfield": "dev-ISSUE-244 as 1.0.0.x-dev",
        "strawberryfield/webform_strawberryfield": "1.0.0.x-dev",
        "swaggest/json-schema": "^0.12.10",
        "symfony/event-dispatcher": "^4",
        "symfony/yaml": "^4",
        "vlucas/phpdotenv": "^5.1",
        "webflo/drupal-finder": "^1.0.0",
        "webmozart/path-util": "^2.3",
        "wikibase/data-model": "9.6.1",
        "zaporylie/composer-drupal-optimizations": "^1.1.1"
    },
```

**Comment by DiegoPino** [comment]
Ha! Why does it not fail here? Mmmmm. OK will check and fix if I figure out what is wrong. Thanks for checking!

**Comment by patdunlavey** [comment]
In [this line](https://github.com/esmero/strawberryfield/blob/1afbc56c16b83cd1f6eafec1b464b5faa21b4d5b/src/Plugin/search_api/processor/Property/StrawberryFlavorAggregatedItemProperty.php#L40), $configuration['processor_ids'] is (already) an empty array.

**Comment by DiegoPino** [comment]
Yep! Fixed and committed, bad default. Sorry!

D


Diego Pino Navarro
Director of Digital Strategy
Archipelago architect
Metropolitan New York Library Council
PO Box 2084
New York, NY 10108

**Comment by patdunlavey** [comment]
Thanks for the quick fix, @DiegoPino! I have tested this to the point of confirming that we get sbf_aggregated_items indexed in solr for both document (multi-page PDF) objects, and creative work series with children, and that these objects are found in site search. The PDF document, which is configured to display using the IAB, shows that internal document search with highlight is working for that viewer. I also successfully set up IAB to display the creative work series collection, and internal IAB search works there as well.

Getting this far required me to precisely set up a lot of configuration pieces - it's not easy! However I am not testing with a new Archi install using the latest templates and views. So I can't comment on what the experience would be like in a new stock Archipelago install. The CWS aggregate indexing did not work until I noticed that I had not yet created the `sbf_file_uri` solr field, and had the wrong indexing types for `top_parent_id` and `parent_sequence_id`. Adding these solr fields requires understanding how to find them, often buried deep in the add-field ajax form. Good documentation for this should be a priority!

@DiegoPino can you think of any additional cases I should test?

**Comment by DiegoPino** [comment]
@patdunlavey I will add an extra pull afterwards that will via a hook update add the other fields Automatically (not the aggregation though) and documentation will be made too before the release. (pinky promise). Please test if you can deleting a child object of an CWS to see if (after reindex happens automagically or you trigger it for the ones that will be retracked) the aggregated field is updated too and has "that" removed OCR also removed 

Thanks so much for testing

**Comment by patdunlavey** [comment]
I added a page to a creative work series and, once the strawberry runners finish, it is added to the sbf_aggregated_items for the parent. However, when I subsequently removed the child object, the parent does not seem to be marked for re-indexing. The `sbf_aggregated_items` field holds onto the deleted child ocr data. When I force reindexing, it fixes itself. The key_value entry for the deleted strawberry flavor is removed when the child object is deleted, but the parent object is not marked for re-indexing. 

Am I right that https://github.com/esmero/strawberryfield/blob/5a3c5f9feed4ff87e17178e836e80403d53c4537/src/EventSubscriber/StrawberryEventDeleteFlavorSubscriber.php#L117 should be doing the work of marking the parent for re-indexing?

**Comment by DiegoPino** [comment]
Yes that should do it. OK, no worries I will debug that... wonder if parent_entity_index_needs_update is not evaluating to TRUE?

**Comment by patdunlavey** [comment]
I actually think/suspect that https://github.com/esmero/strawberryfield/blob/5a3c5f9feed4ff87e17178e836e80403d53c4537/src/EventSubscriber/StrawberryEventDeleteFlavorSubscriber.php#L121 doesn't work. 

Here's my evidence:
I have a parent node that I want to trigger re-indexing on. Here's the search_api_item record:
```
bash-5.1# drush sqlq 'select * from search_api_item where item_id = "entity:node/208:en"'
default_solr_index      entity:node     entity:node/208:en      1669762756      0
```
Note that the status is zero, indicating that it does not need re-indexing.
I ran the following php (using devel/php):
```
$tracking_manager = \Drupal::getContainer()->get('search_api.entity_datasource.tracking_manager');
$parent = \Drupal::entityTypeManager()->getStorage('node')->load(208);
$tracking_manager->entityUpdate($parent);
```
Afterwards, the status value in search_api_item is unchanged, though the timestamp is updated:
```
bash-5.1# drush sqlq 'select * from search_api_item where item_id = "entity:node/208:en"'
default_solr_index      entity:node     entity:node/208:en      1669817060      0
```
Looking at `\Drupal\search_api\Plugin\search_api\datasource\ContentEntityTrackingManager::trackEntityChange` (which is called from `\Drupal\search_api\Plugin\search_api\datasource\ContentEntityTrackingManager::entityUpdate`), it says
```
   * When calling this method with an existing entity
   * (@code $new = FALSE @endcode), changes in the existing translations will
   * only be recognized if an appropriate @code $entity->original @endcode value
   * is set.
```
$new defaults to FALSE. Therefore, I _think_ this will always do nothing unless the current entity is being saved (has $entity->original).

So I'm thinking another method of marking the parent entity for re-indexing may be needed?

**Comment by patdunlavey** [comment]
Would this work?
Replace
```
      foreach ($entity->field_sbf_nodetonode->referencedEntities() as $key => $referencedEntity) {
        $tracking_manager->entityUpdate($referencedEntity);
      }
```
with
```
      foreach ($entity->field_sbf_nodetonode->referencedEntities() as $key => $referencedEntity) {
        $indexes = $tracking_manager->getIndexesForEntity($referencedEntity);
        $datasource_id = 'entity:' . $referencedEntity->getEntityTypeId();
        foreach ($indexes as $index) {
          $index->trackItemsUpdated($datasource_id, [$referencedEntity->id()]);
        }
      }
```

**Comment by DiegoPino** [comment]
Jinx. Yep came to the same conclusion. But sadly means more code because we also need the Language (current) for the entity.

Thanks, Will use your snipped and work around that (wish entityUpdate was less opinionated!)

Diego Pino Navarro
Director of Digital Strategy
Archipelago architect
Metropolitan New York Library Council
PO Box 2084
New York, NY 10108

**Pull request merged**
