### PR TITLE
ISSUE-143 --- added entity type config to EntityJmesPathName, and cor…

### PR DESCRIPTION
**Pull request by patdunlavey**
This PR 

- adds an entity type selection element to the "Entity Reference JmesPath Strawberry Field Key Name Provider" form based on entity types supported by https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php#L33-L42
- replaces 'node' with the the selected entity type in \Plugin\Field\FieldType\StrawberryFieldItem::propertyDefinitions

I understand clearly what the form modification does. I'm less sure what the change in StrawberryFieldItem::propertyDefinitions actually does.

See https://github.com/esmero/strawberryfield/issues/143

### CODE REVIEW

**Comment by patdunlavey** [comment]
I'm not sure if this actually works to make referenced entity attributes and fields indexable in solr - it's likely that don't understand how to configure all the moving parts. We should probably screenshare to make sure I'm performing all the correct steps.

I tried it out with two taxonomy select fields, one of which uses a vocabulary that has a custom field. I added the Entity Reference JmesPath Strawberry Field Key Name Provider (the webform field machine names seen in the ADO json together with the entity type). 

I'm able to add these fields to the solr fields, e.g. `field_descriptive_metadata:obj_adm_price_bundle:body:processed`. 
However:
- Custom fields do not appear in solr's add-field options. 
- When the object is indexed in solr, I see nothing for these fields - not the raw value nor the title or other fields. I only see the webform field name listed in `sm_str_flatten_keys`.

**Comment by DiegoPino** [comment]
Hi, yes, let's do some live testing. I still need to review your code live on a machine, maybe there is something missing? Give me a few hours (sorry) but should be done by 16:00.

**Comment by DiegoPino** [comment]
@patdunlavey in the meantime can you give the pull body (message) a bit of extra info about what is happening in the code? That will help future contributors a lot. Thanks!

**Comment by patdunlavey** [comment]
@DiegoPino I tried to flesh it out just a bit, without going beyond what I actually understand!

**Comment by patdunlavey** [comment]
It turns out my previous testing failures were a combination of various kinds of boneheadedness. I succeeded in getting this all working this morning, with the code in this Born-Digital:ISSUE-143 branch.
I ran code inspection in PhpStorm and it flagged no errors, though a number of warnings (not in new code). Do we care?

**Comment by DiegoPino** [comment]
I do not care about every warning and normally won't expect anyone (except if very deep into the code) to touch more than it is required. Most important as we go further with more contributors are DCS. If you are OK I will merge this into ISSUE-143 and then merge into RC2. If you have any other concerns we can discuss them during our call today too. Thanks a lot, this is good work and will be useful for many other users.

**Review by DiegoPino — APPROVED** [review]
Good. All this is now working and no more code conflicts (because of me too)

**Comment by patdunlavey** [comment]
I found one possible problem. When the webform's term select list is multi-value, the field does not get indexed in solr. The jmespath expression returns an array of values rather than a string.

**Comment by DiegoPino** [comment]
@patdunlavey looking at it. Entity reference fields should allow arrays of entities. I may have missed a check? Does it also happen when nodes? (is member of?)

**Comment by DiegoPino** [comment]
@patdunlavey some updates on this. This is a more complex refactor and I will open another issue for this one. let's roll with this current solution (even if its a single value indexed in Solr) until I find the solution. 

I will bring @pcambra into the issue too since I feel I will have to do some real work on understanding a better way of doing this.

**Comment by DiegoPino** [comment]
See #146

**Pull request merged**
